!<arch>
/               1551377248  0     0     0       246       `
     :  f  ª  >  ‚  ®  !ú  '–  ,â  2  7¢  <Î  BÂ  H&  MÒ  S  XŠ  ^>  cZ  hÞ_isupper _memset _strcat _atoi _isdigit _memcpy _strncat _strchr _strlen _strncpy _islower _puts _strcmp _strspn _isalpha _strpbrk _strstr _abs _strcpy _putchar  0-isupper.o/    1551376391  1000  1000  100664  1264      `
ELF          >                    (          @     @   UH‰å‰}üƒ}ü@~
ƒ}üZ¸   ë¸    ]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010           zR x            !    A†C
\    .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       !                              !                     a                                      '                     a                                      ,      0               a       4                             5                      •                                      J                     ˜       8                              E                      Ø             	                                          Ð       T                                                    è      Ø       
                    	                      À                                                                ñÿ                                                                                                                                                    
             !        0-isupper.c _isupper                         0-memset.o/     1551376392  1000  1000  100664  1288      `
ELF          >                    @          @     @   UH‰åH‰}è‰ð‰UàˆEäÇEü    ë‹UüH‹EèHÂ¶EäˆƒEü‹Eü;EàräH‹Eè]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010         zR x            ;    A†C
v    .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       ;                              !                     {                                      '                     {                                      ,      0               {       4                             5                      ¯                                      J                     °       8                              E                      ð             	                                          è       T                                                           Ø       
                    	                      Ø                                                                ñÿ                                                                                                                                                                 ;        0-memset.c _memset                           0-strcat.o/     1551376392  1000  1000  100664  1368      `
ELF          >                              @     @   UH‰åH‰}èH‰uàÇEø    ÇEü    ëƒEø‹EøHcÐH‹EèHÐ¶ „Àuèë'‹EøHcÐH‹EèHÂ‹EüHcÈH‹EàHÈ¶ ˆƒEüƒEø‹EüHcÐH‹EàHÐ¶ „ÀuÅ‹EøHcÐH‹EèHÐÆ  H‹Eè]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010             zR x            ‡    A†C
‚   .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       ‡                              !                     Ç                                      '                     Ç                                      ,      0               Ç       4                             5                      û                                      J                            8                              E                      @             	                                          8      T                                                    P      Ø       
                    	                      (                                                                ñÿ                                                                                                                                                                 ‡        0-strcat.c _strcat                           100-atoi.o/     1551376392  1000  1000  100664  1544      `
ELF          >                    @          @     @   UH‰åH‰}ØÇEè    ÇEì    ÇEð    ÇEô    ÇEø    ÇEü    ëƒEô‹EôHcÐH‹EØHÐ¶ „ÀuèéÀ   ‹EèHcÐH‹EØHÐ¶ <-uƒEì‹EèHcÐH‹EØHÐ¶ </ŽŒ   ‹EèHcÐH‹EØHÐ¶ <9x‹EèHcÐH‹EØHÐ¶ ¾Àƒè0‰Eü‹Eìƒà…Àt÷]ü‹Uð‰ÐÁàÐÀ‰Â‹EüÐ‰EðÇEø   ‹EèH˜HPH‹EØHÐ¶ </~4‹EèH˜HPH‹EØHÐ¶ <9ÇEø    ƒEè‹Eè;Eô}
ƒ}ø „.ÿÿÿƒ}ø u¸    ë‹Eð]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010               zR x            5   A†C
0  .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       5                             !                     u                                     '                     u                                     ,      0               u      4                             5                      ©                                     J                     °      8                              E                      ð             	                                          è      T                                                           Ø       
                    	                      Ø                                                                ñÿ                                                                                                                                                                 5       100-atoi.c _atoi                             1-isdigit.o/    1551376392  1000  1000  100664  1264      `
ELF          >                    (          @     @   UH‰å‰}üƒ}ü/~
ƒ}ü9¸   ë¸    ]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010           zR x            !    A†C
\    .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       !                              !                     a                                      '                     a                                      ,      0               a       4                             5                      •                                      J                     ˜       8                              E                      Ø             	                                          Ð       T                                                    è      Ø       
                    	                      À                                                                ñÿ                                                                                                                                                    
             !        1-isdigit.c _isdigit                         1-memcpy.o/     1551376392  1000  1000  100664  1296      `
ELF          >                    H          @     @   UH‰åH‰}èH‰uà‰UÜÇEü    ë‹UüH‹EèHÂ‹MüH‹EàHÈ¶ ˆƒEü‹Eü;EÜrÛH‹Eè]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010         zR x            C    A†C
~    .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       C                              !                     ƒ                                      '                     ƒ                                      ,      0               ƒ       4                             5                      ·                                      J                     ¸       8                              E                      ø             	                                          ð       T                                                          Ø       
                    	                      à                                                                ñÿ                                                                                                                                                                 C        1-memcpy.c _memcpy                           1-strncat.o/    1551376392  1000  1000  100664  1376      `
ELF          >                    ˜          @     @   UH‰åH‰}èH‰uà‰UÜÇEø    ÇEü    ëƒEø‹EøHcÐH‹EèHÐ¶ „Àuèë'‹EøHcÐH‹EèHÂ‹EüHcÈH‹EàHÈ¶ ˆƒEøƒEü‹EüHcÐH‹EàHÐ¶ „Àt‹Eü;EÜ|½‹EøHcÐH‹EèHÐÆ  H‹Eè]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010          zR x            ’    A†C
   .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       ’                              !                     Ò                                      '                     Ò                                      ,      0               Ò       4                             5                                                           J                           8                              E                      H             	                                          @      T                                                    X      Ø       
                    	                      0                                                                ñÿ                                                                                                                                                    
             ’        1-strncat.c _strncat                         2-strchr.o/     1551376392  1000  1000  100664  1296      `
ELF          >                    H          @     @   UH‰åH‰}è‰ðˆEäH‹EèHPH‰Uè¶ ¾À‰Eü¾Eä;Eüu
H‹EèHƒèëƒ}ü uÒ¸    ]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010          zR x            B    A†C
}    .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       B                              !                     ‚                                      '                     ‚                                      ,      0               ‚       4                             5                      ¶                                      J                     ¸       8                              E                      ø             	                                          ð       T                                                          Ø       
                    	                      à                                                                ñÿ                                                                                                                                                                 B        2-strchr.c _strchr                           2-strlen.o/     1551376392  1000  1000  100664  1280      `
ELF          >                    8          @     @   UH‰åH‰}èÇEü    ëƒEü‹EüHcÐH‹EèHÐ¶ „Àuè‹Eü]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010              zR x            .    A†C
i    .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       .                              !                     n                                      '                     n                                      ,      0               n       4                             5                      ¢                                      J                     ¨       8                              E                      è             	                                          à       T                                                    ø      Ø       
                    	                      Ð                                                                ñÿ                                                                                                                                                                 .        2-strlen.c _strlen                           2-strncpy.o/    1551376392  1000  1000  100664  1352      `
ELF          >                    €          @     @   UH‰åH‰}èH‰uà‰UÜÇEü    ë#‹EüHcÐH‹EèHÂ‹EüHcÈH‹EàHÈ¶ ˆƒEü‹EüHcÐH‹EàHÐ¶ „Àt‹Eü;EÜ|Áë‹EüHcÐH‹EèHÐÆ  ƒEü‹Eü;EÜ|äH‹Eè]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010         zR x            {    A†C
v   .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       {                              !                     »                                      '                     »                                      ,      0               »       4                             5                      ï                                      J                     ð       8                              E                      0             	                                          (      T                                                    @      Ø       
                    	                                                                                      ñÿ                                                                                                                                                    
             {        2-strncpy.c _strncpy                         3-islower.o/    1551376392  1000  1000  100664  1264      `
ELF          >                    (          @     @   UH‰å‰}üƒ}ü`~
ƒ}üz¸   ë¸    ]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010           zR x            !    A†C
\    .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       !                              !                     a                                      '                     a                                      ,      0               a       4                             5                      •                                      J                     ˜       8                              E                      Ø             	                                          Ð       T                                                    è      Ø       
                    	                      À                                                                ñÿ                                                                                                                                                    
             !        3-islower.c _islower                         3-puts.o/       1551376392  1000  1000  100664  1464      `
ELF          >                    `          @     @  	 UH‰åHƒì H‰}èÇEü    ë‹EüHcÐH‹EèHÐ¶ ¾À‰Çè    ƒEü‹EüHcÐH‹EèHÐ¶ „ÀuÎ¿
   è    ÉÃ GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010        zR x            T    A†C
O   .symtab .strtab .shstrtab .rela.text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                              @       T                                                    p      0       
                    &                     ”                                      ,                     ”                                      1      0               ”       4                             :                      È                                      O                     È       8                              J                                    
                                                 Y                                                    `      ð                           	                      P                                                                ñÿ                                                                                                                                                    
             T                              3-puts.c _puts _putchar        +          	   üÿÿÿÿÿÿÿM          	   üÿÿÿÿÿÿÿ                      3-strcmp.o/     1551376392  1000  1000  100664  1320      `
ELF          >                    `          @     @   UH‰åH‰}øH‰uðëH‹Eø¶ „Àu¸    ë4HƒEøHƒEðH‹Eø¶H‹Eð¶ 8ÂtÒH‹Eø¶ ¾ÐH‹Eð¶ ¾À)Â‰Ð]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010              zR x            V    A†C
Q   .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       V                              !                     –                                      '                     –                                      ,      0               –       4                             5                      Ê                                      J                     Ð       8                              E                                   	                                                T                                                           Ø       
                    	                      ø                                                                ñÿ                                                                                                                                                                 V        3-strcmp.c _strcmp                           3-strspn.o/     1551376392  1000  1000  100664  1392      `
ELF          >                    ¨          @     @   UH‰åH‰}èH‰uàÇEø    ÇEð    ëfÇEü    ÇEô    ë3‹EðHcÐH‹EèHÐ¶‹EôHcÈH‹EàHÈ¶ 8ÂuƒEøÇEü   ƒEô‹EôHcÐH‹EàHÐ¶ „Àu¹ƒ}ü u‹EøëƒEð‹EðHcÐH‹EèHÐ¶ „Àu†¸    ]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010               zR x                A†C
˜   .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @                                     !                     Ý                                      '                     Ý                                      ,      0               Ý       4                             5                                                           J                           8                              E                      X             	                                          P      T                                                    h      Ø       
                    	                      @                                                                ñÿ                                                                                                                                                                         3-strspn.c _strspn                           4-isalpha.o/    1551376392  1000  1000  100664  1280      `
ELF          >                    8          @     @   UH‰å‰}üƒ}ü`~ƒ}üz~ƒ}ü@~
ƒ}üZ¸   ë¸    ]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010               zR x            -    A†C
h    .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       -                              !                     m                                      '                     m                                      ,      0               m       4                             5                      ¡                                      J                     ¨       8                              E                      è             	                                          à       T                                                    ø      Ø       
                    	                      Ð                                                                ñÿ                                                                                                                                                    
             -        4-isalpha.c _isalpha                         4-strpbrk.o/    1551376392  1000  1000  100664  1344      `
ELF          >                    x          @     @   UH‰åH‰}èH‰uàÇEø    ëKÇEü    ë%H‹Eè¶‹EüHcÈH‹EàHÈ¶ 8ÂuH‹Eèë1ƒEü‹EüHcÐH‹EàHÐ¶ „ÀuÇHƒEèƒEøH‹Eè¶ „Àuª¸    ]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010          zR x            r    A†C
m   .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       r                              !                     ²                                      '                     ²                                      ,      0               ²       4                             5                      æ                                      J                     è       8                              E                      (             	                                                 T                                                    8      Ø       
                    	                                                                                      ñÿ                                                                                                                                                    
             r        4-strpbrk.c _strpbrk                         5-strstr.o/     1551376392  1000  1000  100664  1400      `
ELF          >                    °          @     @   UH‰åH‰}èH‰uàÇEø    ëtÇEü    ë-‹Uø‹EüÐHcÐH‹EèHÐ¶‹EüHcÈH‹EàHÈ¶ 8ÂuƒEü‹EüHcÐH‹EàHÐ¶ „Àu¿ë‹EüHcÐH‹EàHÐ¶ „Àu‹EøHcÐH‹EèHÐë!ƒEø‹EøHcÐH‹EèHÐ¶ „À…tÿÿÿ¸    ]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010            zR x            ¨    A†C
£   .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       ¨                              !                     è                                      '                     è                                      ,      0               è       4                             5                                                           J                            8                              E                      `             	                                          X      T                                                    p      Ø       
                    	                      H                                                                ñÿ                                                                                                                                                                 ¨        5-strstr.c _strstr                           6-abs.o/        1551376392  1000  1000  100664  1248      `
ELF          >                               @     @   UH‰å‰}üƒ}ü x‹Eüë‹Eü÷Ø]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010           zR x                A†C
T    .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @                                     !                     Y                                      '                     Y                                      ,      0               Y       4                             5                                                            J                            8                              E                      È             	                                          È       T                                                    à      Ø       
                    	                      ¸                                                                ñÿ                                                                                                                                                    	                     6-abs.c _abs                         9-strcpy.o/     1551376392  1000  1000  100664  1352      `
ELF          >                    €          @     @   UH‰åH‰}èH‰uàÇEø    ëƒEø‹EøHcÐH‹EàHÐ¶ „ÀuèÇEü    ë#‹EüHcÐH‹EèHÂ‹EüHcÈH‹EàHÈ¶ ˆƒEü‹Eü;Eø|Õ‹EüHcÐH‹EèHÐÆ  H‹Eè]Ã GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010             zR x            w    A†C
r   .symtab .strtab .shstrtab .text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                          @       w                              !                     ·                                      '                     ·                                      ,      0               ·       4                             5                      ë                                      J                     ð       8                              E                      0             	                                          (      T                                                    @      Ø       
                    	                                                                                      ñÿ                                                                                                                                                                 w        9-strcpy.c _strcpy                           _putchar.o/     1551376392  1000  1000  100664  1400      `
ELF          >                    8          @     @  	 UH‰åHƒì‰øˆEüHEüº   H‰Æ¿   è    ÉÃ GCC: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010               zR x            %    A†C
`    .symtab .strtab .shstrtab .rela.text .data .bss .comment .note.GNU-stack .rela.eh_frame                                                                                              @       %                                                    H             
                    &                     e                                      ,                     e                                      1      0               e       4                             :                      ™                                      O                             8                              J                      `             
                                          Ø       Y                                                    8      ð                           	                      (                                                                ñÿ                                                                                                                                                                 %                              _putchar.c _putchar write                	   üÿÿÿÿÿÿÿ                      
